version: "3"
networks:
  laravel:
services:
  nginx:
    command: [nginx-debug, '-g', 'daemon off;']
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    networks:
      - laravel
    depends_on:
      - php
      - mysql
    volumes:
      - ./src/laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    tty: true 
    image: mysql
    ports:
      - 4306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - laravel
    environment:
      MYSQL_DATABASE: home
      MYSQL_ROOT_PASSWORD: secrete
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    container_name: mysql

  php:
    tty: true
    container_name: laravel
    ports:
      - 9000:9000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/laravel:/var/www/html
    networks:
      - laravel